name: Cypress cloud

on: 
  workflow_dispatch:
    inputs: 
      spec:
        description: Run by cypress command line
        default: cypress/e2e/*

jobs:
  cypess-e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with: 
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env: 
          CYPRESS_RECORD_KEY: f11e7787-248d-4113-9da4-860d30558aeb
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
